[package]
name = "pumpkin-build"
version.workspace = true
edition.workspace = true

[dependencies]
reqwest = { version = "0.12.9", features = ["blocking"] }
zip = "2.2.0"
tempfile = "3.13.0"
serde = "1.0.214"
serde_json = "1.0.132"